import type { PathSchemaMap } from './path-schema-map-generator.js';

/**
 * Generate .remarkrc.generated.mjs content from path-schema map.
 */
export function generateRemarkConfig(pathSchemaMap: PathSchemaMap): string {
  const schemaEntries = Object.entries(pathSchemaMap.mappings)
    .map(([glob, schemaPath]) => `      '${glob}': '${schemaPath}'`)
    .join(',\n');

  return `// Generated by pkf-processor - DO NOT EDIT
// Generated: ${pathSchemaMap.generated}

import remarkFrontmatter from 'remark-frontmatter';
import remarkLintFrontmatterSchema from 'remark-lint-frontmatter-schema';
import remarkValidateLinks from 'remark-validate-links';

const remarkConfig = {
  plugins: [
    remarkFrontmatter,
    [
      remarkLintFrontmatterSchema,
      {
        schemas: {
${schemaEntries}
        },
      },
    ],
    remarkValidateLinks,
  ],
};

export default remarkConfig;
`;
}
